## Numpy Questions Solved

In [2]:
# 1. Import the numpy package under the name

import numpy as np

In [3]:
# 2. Print the numpy version and the configuration

print(np.__version__)
np.show_config()

1.20.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']


In [4]:
# 3. Create a null vector of size 10

print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# 4. How to find the memory size of any array

a = np.zeros(5)
print("%d bytes" % (a.size * a.itemsize))

40 bytes


In [6]:
# 5. How to get the documentation of the numpy add function from the command line

#python -c "import numpy; numpy.info(numpy.add)"

In [7]:
# 6. Create a null vector of size 10 but the fifth value which is 1

b = np.zeros(10)
b[4] = 1
print(b)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
# 7. Create a vector with values ranging from 10 to 49

c = np.arange(10,50)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
# 8. Reverse a vector (first element becomes last)

d = np.arange(1,16)
d = d[::-1]
print(d)

[15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [10]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8

e = np.arange(9).reshape(3,3)
print(e)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]

f = np.nonzero([1,2,0,0,4,0])
print(f)

(array([0, 1, 4], dtype=int64),)


In [12]:
# 11. Create a 3x3 identity matrix

g = np.eye(3)
print(g)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# 12. Create a 3x3x3 array with random values

h = np.random.random((3,3,3))
print(h)

[[[0.67973063 0.60913863 0.86866236]
  [0.47784011 0.6069558  0.33552066]
  [0.29246699 0.96549468 0.51092978]]

 [[0.37392137 0.98746752 0.08686424]
  [0.60575894 0.35534808 0.33276194]
  [0.55904708 0.95489536 0.12277523]]

 [[0.41354445 0.38634236 0.86444403]
  [0.00299828 0.68567482 0.42368702]
  [0.95098047 0.21856679 0.08320028]]]


In [14]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values

i = np.random.random((10,10))
print(i)
min , max = i.min() , i.max()
print(min, 'is the min value &',max, 'is the max value')

[[0.36036802 0.20965939 0.23498323 0.65225851 0.05620493 0.59653761
  0.80857565 0.25647442 0.49804009 0.50051535]
 [0.08322706 0.1122238  0.2162227  0.89584519 0.96604745 0.40443743
  0.24388506 0.9117909  0.83953644 0.35809896]
 [0.7293732  0.60355328 0.21611486 0.8603635  0.06650819 0.75608632
  0.28576055 0.63222105 0.3767654  0.95202765]
 [0.42237949 0.84418278 0.76064737 0.20298543 0.67398216 0.21479345
  0.92639909 0.38897403 0.63927833 0.62836501]
 [0.98320612 0.9012107  0.80080884 0.65818668 0.96060183 0.59541721
  0.16916804 0.8055805  0.27537915 0.94679649]
 [0.15238066 0.34644789 0.19326616 0.5131513  0.50619865 0.19897046
  0.7035879  0.87756728 0.87764238 0.10169179]
 [0.6496919  0.79062216 0.564616   0.95254514 0.20455158 0.99578218
  0.53902095 0.4779025  0.97348534 0.61915014]
 [0.4051169  0.4534762  0.03266223 0.10525395 0.85920939 0.63158625
  0.69994588 0.36743578 0.07663813 0.7998658 ]
 [0.00789144 0.94339944 0.5819931  0.02584357 0.389817   0.98796729
  0.08977076

In [15]:
# 14. Create a random vector of size 30 and find the mean value

j = np.random.random(30)
print(j)
mean = j.mean()
print(mean)

[0.05910583 0.32391086 0.3507262  0.02584153 0.62396683 0.07425387
 0.95704257 0.70481893 0.230777   0.3526811  0.63532495 0.43515841
 0.72488492 0.01633125 0.60641556 0.24386441 0.49277066 0.87134169
 0.23928911 0.7126106  0.75841471 0.10809691 0.96684128 0.10353306
 0.53140906 0.45654522 0.19852557 0.25369438 0.57320262 0.57562179]
0.4402333629707945


In [16]:
# 15. Create a 2d array with 1 on the border and 0 inside

k = np.ones((3,3),dtype=int)
k[1,1] = 0
print(k)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [17]:
# 16. How to add a border (filled with 0's) around an existing array

l = np.ones((3,3),dtype=int)
l = np.pad(l, pad_width=1, mode='constant', constant_values=0)
print(l)

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [18]:
''' 17. What is the result of the following expression
    
    0 * np.nan
    np.nan == np.nan
    np.inf > np.nan
    np.nan - np.nan
    np.nan in set([np.nan])
    0.3 == 3 * 0.1
'''
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


In [19]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

m = np.diag(1+np.arange(4),k=-1)
print(m)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [20]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern

n = np.zeros((8,8),dtype=int)
n[1::2,::2] = 1
n[::2,1::2] = 1
print(n)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [21]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element

print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [22]:
# 21. Create a checkerboard 8x8 matrix using the tile function

p = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(p)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [23]:
# 22. Normalize a 5x5 random matrix

q = np.random.random((5,5))
q = (q - np.mean (q)) / (np.std (q))
print(q)

[[ 0.7640253  -0.86318973  0.05732742  0.83501972  1.06323655]
 [ 0.95567044 -0.90311544 -0.07993038 -1.12309917  1.19997234]
 [ 0.92997593 -1.9466309   0.79315864 -1.28153246  1.29463771]
 [-0.90888408  1.25560802  0.11227934 -0.59244379 -0.49693922]
 [ 0.68712712 -2.23179885  0.54211975  0.10963816 -0.17223242]]


In [26]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [27]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

r = np.dot(np.ones((5,3)), np.ones((3,2)))
print(r)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [28]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

s = np.arange(11)
s[(3 < s) & (s < 8)] *= -1
print(s)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [29]:
'''
26. What is the output of the following script

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
'''
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [63]:
'''
27. Consider an integer vector Z, which of these expressions are legal?
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
'''
Z = np.array([3])
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[27]
[4]
[False]
[0.+3.j]
[3.]
[False]


In [32]:
'''
28. What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
'''

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\DELL\AppData\Local\Temp/ipykernel_6016/1674967665.py:8: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\DELL\AppData\Local\Temp/ipykernel_6016/1674967665.py:9: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [33]:
# 29. How to round away from zero a float array ?

t = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(t)), t))

[ 1.  9.  2. -6.  6.  9. -2. -8.  6. -9.]


In [34]:
# 30. How to find common values between two arrays?

a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(np.intersect1d(a,b))

[2 3]


In [ ]:
# 31. How to ignore all numpy warnings (not recommended)?

'''
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0
'''

In [35]:
# 32. Is the following expressions true
# np.sqrt(-1) == np.emath.sqrt(-1)

np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\DELL\AppData\Local\Temp/ipykernel_6016/2980492941.py:4: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [38]:
# 33. How to get the dates of yesterday, today and tomorrow

yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print(yesterday)
print(today)
print(tomorrow)

2022-08-21
2022-08-22
2022-08-23


In [39]:
# 34. How to get all the dates corresponding to the month of July 2016

u = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(u)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [40]:
# 35. How to compute ((A+B)*(-A/2)) in place (without copy)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

print(np.multiply(A,B,out=A))

[-4.5 -4.5 -4.5]


In [41]:
# 36. Extract the integer part of a random array of positive numbers using 4 different methods

v = np.random.uniform(0,10,10)

print(v - v%1)
print(v // 1)
print(np.floor(v))
print(v.astype(int))
print(np.trunc(v))

[6. 0. 7. 4. 8. 3. 5. 5. 2. 5.]
[6. 0. 7. 4. 8. 3. 5. 5. 2. 5.]
[6. 0. 7. 4. 8. 3. 5. 5. 2. 5.]
[6 0 7 4 8 3 5 5 2 5]
[6. 0. 7. 4. 8. 3. 5. 5. 2. 5.]


In [42]:
# 37. Create a 5x5 matrix with row values ranging from 0 to 4

w = np.zeros((5,5))
w += np.arange(5)
print(w)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [45]:
# 38. Consider a generator function that generates 10 integers and use it to build an array

def generate():
    for x in range(10):
        yield x
z = np.fromiter(generate(),dtype=float,count=-1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [46]:
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

x = np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [47]:
# 40. Create a random vector of size 10 and sort it

y = np.random.random(10)
y.sort()
print(y)

[0.04639294 0.05809158 0.06281485 0.10742065 0.17693906 0.38186977
 0.66466645 0.75366949 0.82249083 0.88212032]


In [48]:
# 41. How to sum a small array faster than np.sum

z = np.arange(10)
np.add.reduce(z)

45

In [50]:
# 42. Consider two random array A and B, check if they are equal

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.array_equal(A,B)
print(equal)

False


In [52]:
# 43. Make an array immutable (read-only)

a = np.zeros(5)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

In [53]:
# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.99705367 0.31469591 0.51787293 0.68714029 0.89226439 0.91996875
 0.40069125 1.00291557 1.04950974 0.80959329]
[0.17429908 0.36674811 1.45247263 0.8019784  0.18995682 1.27586347
 1.06638276 0.08650804 1.22249493 0.6076535 ]


In [54]:
# 45. Create random vector of size 10 and replace the maximum value by 0

Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.0115476  0.44621282 0.         0.40303898 0.25266833 0.06424699
 0.63622686 0.49164152 0.49883945 0.08754213]


In [55]:
# 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [56]:
# 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [57]:
# 48. Print the minimum and maximum representable value for each numpy scalar type

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [60]:
# 49. How to print all the values of an array

Z = np.zeros((5,5))
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [61]:
# 50. How to find the closest value (to a given scalar) in a vector

Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

58
